### ISSUE TITLE
Icon for Rydbot

### ISSUE THREAD

**Issue by hafizahmmed** [zedtang/RydeBot#4]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![rydebot-01](https://user-images.githubusercontent.com/38810169/40103477-61281f50-590f-11e8-9cb8-e11b32c1aee2.png)

**Comment by zedtang** [comment]
Wow, this looks great! Yes, we would like to use this as our app icon if that's ok with you.  Thank you so much!

**Comment by hafizahmmed** [comment]
source file
https://drive.google.com/open?id=1qBHhIfupI9GoSmlyiY2-0VBQvWrGciF5
